

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.80.192:3306/shkb
    username: shkb
    password: shkb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
server:
  port: 8080
logging:
  file:
    path: /var/log/shkb
