spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shkb
    username: shkb
    password: shkb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost
    port: 6379
    password: shkb
    timeout: 200
#  cache:
#    type: ehcache
#    ehcache:
#      config: classpath:/ehcache.xml

