spring:
  profiles:
    active: prod


server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 400KB
    mime-types: [application/json]

logging:
  file:
    path: /var/log/shkb

